name: Create Next.js Project

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Name of the Next.js project'
        required: true
        type: string
  repository_dispatch:
    types: [create-next-app]

jobs:
  create-next-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug Information
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "GitHub event:"
          cat $GITHUB_EVENT_PATH
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Check if Next.js project exists
        id: check-project
        run: |
          if [ -f "package.json" ] && grep -q "next" "package.json"; then
            echo "Next.js project already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Next.js project does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Clean up existing files
        if: steps.check-project.outputs.exists == 'false'
        run: |
          # 현재 디렉토리의 모든 파일과 디렉토리를 삭제 (git 관련 파일 제외)
          find . -mindepth 1 -not -name '.git' -not -name '.github' -exec rm -rf {} +
          
      - name: Create Next.js Project
        if: steps.check-project.outputs.exists == 'false'
        run: |
          echo "Creating Next.js project in current directory"
          npx create-next-app@latest . --typescript --tailwind --eslint --src-dir --app --import-alias "@/*" --yes
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Commit and Push Changes
        run: |
          echo "Current directory after create-next-app:"
          ls -la
          git status
          git add .
          git commit -m "Initialize Next.js project"
          git push origin main